### ISSUE TITLE
Trigger on button double-click

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-radiora2#18]
Just that.

**Comment by FlyingDiver** [comment]
Detecting the double-click is easy, as is having distinct triggers for it.

The hard part is NOT triggering single-click triggers.

**Comment by rapamatic** [comment]
The way I setup my double clicks, they tend to be an additional action to take sequentially with the single click. So, for example, one click on the off button by our master door turns off the room, a double click also turns off the master bath, and a triple click turns off the whole second floor. I think it’s best practice to have a single click scene programmed in RR2 so that if Indigo fails the button still works.....

So in my examples, and the way I do double and triple clicks, I expect the single click action to occur before the double click. If you try to detect a double click independently, then you are probably going to introduce a noticable lag in responding to single clicks or have to really play around with your timeouts... I guess you could expose a few timeout variables to be configured for each button, but’s that’s adding a lot of complexity to the trigger...

I wonder how Homeworka handles double clicks? Is it a separate action that occurs without the single click action firing?

**Comment by FlyingDiver** [comment]
Available in Beta 12, per Rapamatic's usage scenario.
