### ISSUE TITLE
Lutron triggers and button #7

### ISSUE THREAD

**Issue by smuseby** [FlyingDiver/Indigo-radiora2#55]
I modified a keypad in Essentials > Design to configure the keypad for 7 buttons. When I create the devices from the repeater with the Lutron plug-in, there is a new device, keypad button 7, modeled after the raise (or lower?) button '.18.
When creating a new trigger, I don't believe the new button 7 is listed in the available buttons; the '.18 and '.19 are listed, but in at least one of my keypads, indigo does not respond to either one.

**Comment by FlyingDiver** [comment]
Not sure what you mean by "modeled after the raise (or lower?) button '.18."  When I change one of my keypads to a W7B (instead of a W6RL), I just get a button 7, similar to buttons 1-6.  But no matching LED device.

If you didn't delete the raise and lower buttons (18 and 19), then they'll still be in the popup.  The plugin does not delete devices that no longer exist.   Those buttons no longer exist on the Lutron side, so you'll never get a notification for them.

Button 7 was certainly listed for me:

<img width="519" alt="Screen Shot 2022-09-06 at 9 44 19 PM" src="https://user-images.githubusercontent.com/72976/188771803-dc2f8b1a-b85c-4139-8c36-e1ba46bf1a84.png">

I do not have any W7B keypads, so I can't test whether they actually send out a status that the plugin can act on.  You can test that yourself by enabling debug logging (not detailed debugging), and see if you get a sequence like this when you press the button:
```
   Lutron RRA2/Caséta Debug        Received a keypad button/LED status message: ~DEVICE,11,5,3
   Lutron RRA2/Caséta Debug        buttonTriggerCheck: deviceID: 11, componentID: 5, gatewayID: 4452640
   Lutron RRA2/Caséta Debug        Received a keypad button/LED status message: ~DEVICE,11,5,4
   Lutron RRA2/Caséta Debug        buttonMultiPressCheck: Timeout reached for keypadid = 4452640:11.5, presses = 1
```

The componentID should be 7.

**Comment by smuseby** [comment]
Joe - Sorry to be so slow replying - I've had some medical issues.
I just performed the debug test you suggested: For a 6 button keypad, I get
the same event log messages you quoted; for a keypad I configured in
Essentials to W7B (and transferred), neither the up nor the down buttons
are recognized with an entry in the event log. - also true for a
simultaneous press of both buttons.
Please let me know if the 7th button can't be used - I'm laying out my
keypads now, and need to know before I order engraving.
Thanks,
Bob

**Comment by FlyingDiver** [comment]
If there's nothing in the log then the plugin isn't being notified and there's nothing I can do about it.

**Comment by smuseby** [comment]
That doesn't make sense. Other than no LED, the seventh button is the same. Why would there be a 7 button keypad if it doesn't send a signal. In Essentials, I specified a W7B button kit on the Design page. Perhaps when installing the physical 7B keypad, it enables the 7th button? I was just reminded of another possibility: my Lutron Repeater regularly loses connection after a transfer, which requires power cycling and a long wait.
I haven't given up on button 7.
