### ISSUE TITLE
Auto-create devices based on repeater device list

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-radiora2#9]
Yeah, just that.

**Comment by rapamatic** [comment]
Here is my XML file. I've got a VCRX and fan controls. No RR2 t-stats though.

I also have a virtual tabletop keypad - I've been having issues with the LED IDs on that being out of bounds (the range of button and LED IDs is different than for a regular keypad), so maybe the info will be helpful there too.
[DbXmlInfo.xml.html.zip](https://github.com/FlyingDiver/Indigo-radiora2/files/1825732/DbXmlInfo.xml.html.zip)

**Comment by FlyingDiver** [comment]
Beta version released that implements this.  Needs further testing with additional device types.

**Comment by FlyingDiver** [comment]
The offset between button component numbers and LED component numbers is the same on the tabletop keypad as the other keypads.  If there's something else going on, I'll need more details.  Maybe open another issue?

**Comment by FlyingDiver** [comment]
Beta 2 is available now.

**Comment by FlyingDiver** [comment]
Rap - would you be willing to run Beta 2 on your system?  Just create a new empty Indigo database so you're not messing with your live one.  Have it create the devices and then look it over to see if everything is set up as expected.

The only thing I have no way to do is select the behavior for the LED state (LED or follow button) since that's purely an Indigo concept and not in the Lutron XML.

**Comment by FlyingDiver** [comment]
Crap.  Deleting Beta 2 for now.

**Comment by FlyingDiver** [comment]
OK, Beta 2 is back.  Please test.

**Comment by rapamatic** [comment]
The issue with the tabletop keypads wasn't the offset, the issue was the internal data checks in the plugin that expected the ID for an LED to only be in the range of 81-87 and a button to be in the range of 1-7... for a tabletop keypad those IDs can range from 1-17 and the LEDs from 81-97....

I'll run some tests with beta 2 now and report any issues

**Comment by FlyingDiver** [comment]
Ah, gotcha.  I'll look into it.  That code pre-dates my involvement with this plugin.  ;)

**Comment by FlyingDiver** [comment]
I can't find anything that actually checks those limits.  There's text in the device creation dialog, but nothing that actually does anything about it.  That. I can find.  If you run checks and can get an error, please create a new issue.

**Comment by rapamatic** [comment]
When trying to run a simulated create, I'm seeing this error in debugging:

```
Exception in thread Thread-2:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "plugin.py", line 1238, in createAllDevices
    if use_local:
NameError: global name 'use_local' is not defined
```

The plugin seems to hang at this point, and I need to force reset

**Comment by FlyingDiver** [comment]
Yeah, I just fixed that.  I'll post another version.

**Comment by FlyingDiver** [comment]
Beta 3 is available.

**Comment by rapamatic** [comment]
Ok, this time it executed correctly. A few notes:

- All devices were in off state after I auto-created the devices (I don't know if its feasible to do a full status recheck after the auto discovery?)
- You are able to pull the name of dimmers, fans, etc - any way to pull the button labels automatically?

The auto-setup worked well with my stuff:
- It pulled all the buttons correctly from the tabletop dimmer
- Fans were correctly setup
- VCRX inputs showed up under sensors and outputs under switches, which makes sense

**Comment by FlyingDiver** [comment]
> All devices were in off state after I auto-created the devices (I don't know if its feasible to do a full status recheck after the auto discovery?)

Done

> You are able to pull the name of dimmers, fans, etc - any way to pull the button labels automatically?

Done.

**Comment by rapamatic** [comment]
Great, both of those are working well for me.

But it looks like tabletop support has introduced a new bug, and I don't know if I just missed this before, or if it is new in beta 4. The code is adding buttons (and LEDs) for the raise/lower buttons on the keypad... I guess on the surface there is nothing wrong with that, but these buttons should not have LEDs created for them (since they don't have LEDs on the physical buttons) and since there is no engraving for these buttons, perhaps it is best to hard code the labels for these specific IDs:

For standard keypads:
16 - Top Lower
17 - Top Raise
18 - Bottom Lower
19 - Bottom Raise

For tabletop:
20 - Column 1 lower
21 - column 1 raise
22 - column 2 lower
23 - column 2 raise
24 - column 3 lower
25 - column.3 raise

The code does appear to only create these raise/lower buttons as they exist on the keypads, so it would probably be a good idea to put them in - just need to hard code the names and omit the LEDs... 

Unfortunately, there is some overlap between Button IDs, since a tabletop button ID can range 1-17, so we probably need some check to determine if it is a wall keypad or a tabletop... I don't know if there is something in the XML that would indicate that, or if we need some sort of logic in the code to test it (perhaps based on the presence of button IDs 24 and 25 (it appears every tabletop keypad layout (per page 110 of the integration protocol) has column 3 raise/lower buttons.

**Comment by FlyingDiver** [comment]
The device type is specific, so I'll just need to key off that when creating buttons.

**Comment by FlyingDiver** [comment]
Moved your last report to it's own issue.  Closing this one because I think I'm feature complete, except for bugs not yet found.

**Comment by gt3mike** [comment]
I see this is closed, but I only just saw your request for RR2 data. Would it still be helpful/useful if I sent you my XML?

**Comment by FlyingDiver** [comment]
Yes, please.  You might have different devices than I've gotten so far.

**Comment by gt3mike** [comment]
[DbXmlInfo.xml.zip](https://github.com/FlyingDiver/Indigo-radiora2/files/1859549/DbXmlInfo.xml.zip)
Here you go.
